"""Task recorder.

Captures every successful UI action the LLM-driven Executor took on a
goal, plus enough context to *replay* it later without invoking the
LLM:

  • screen_signature  — a fingerprint of the pre-action screen (the
                        elements that were actually present), used at
                        replay time to confirm we're on the same step
  • action            — what to do (kind + target + target_kind)
  • input_value       — for `type` actions, with placeholders preserved
                        (`<USER_NAME>`, `<USER_EMAIL>`, …) so the
                        replayer can re-generate fresh values
  • verification_anchors — short, stable element labels that should
                        appear AFTER the action succeeds. The replayer
                        uses these to verify the step worked.

A `RecordedTask` holds the goal, plan milestones, and the ordered list
of `RecordedAction`s. The library serializes it to JSON.
"""

from __future__ import annotations

import hashlib
import logging
import re
import time
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set

from pydantic import BaseModel, Field

from .device_manager import Observation
from .planner import PlanStep
from .ui_parser import UIElement, parse_hierarchy

log = logging.getLogger(__name__)


# --------------------------------------------------------------------------- #
# Public models (stored in JSON)
# --------------------------------------------------------------------------- #

# Placeholders the recorder treats as DYNAMIC fields. At replay time
# these get re-generated by `DynamicValueResolver` so the macro never
# pastes the same fake name/email twice.
_PLACEHOLDER_RX = re.compile(r"<([A-Z][A-Z0-9_]+)>")


class RecordedAction(BaseModel):
    """One step of a recorded task."""

    step_index: int                      # 1-based ordinal
    milestone_id: Optional[int] = None
    milestone_text: str = ""
    screen_signature: str                # 16-char hash of key elements pre-action
    screen_summary: str = ""             # human-readable, from LLM (debug aid)
    action_kind: str                     # click | type | press | open_app | scroll_to | wait | back
    target: str = ""
    target_kind: str = "text"
    input_value: str = ""
    is_dynamic: bool = False             # true when input_value contains <PLACEHOLDER>
    dynamic_fields: List[str] = Field(default_factory=list)   # ["USER_NAME"]
    verification_anchors: List[str] = Field(default_factory=list)
    is_recovery: bool = False            # true when the LLM dismissed an unrelated popup

    @classmethod
    def detect_dynamic(cls, value: str) -> List[str]:
        return list(dict.fromkeys(_PLACEHOLDER_RX.findall(value or "")))


class RecordedTask(BaseModel):
    """A successfully-completed task ready for replay."""

    schema_version: int = 1
    goal: str
    created_at: float = Field(default_factory=time.time)
    llm_provider: str = ""
    llm_model: str = ""
    plan_milestones: List[dict] = Field(default_factory=list)
    actions: List[RecordedAction] = Field(default_factory=list)
    notes: str = ""

    # ---- helpers --------------------------------------------------------- #

    def task_id(self) -> str:
        """Stable 8-char id derived from the goal text."""
        return hashlib.sha1(self.goal.lower().strip().encode("utf-8")).hexdigest()[:8]

    def has_dynamic_fields(self) -> bool:
        return any(a.is_dynamic for a in self.actions)


# --------------------------------------------------------------------------- #
# Screen signature
# --------------------------------------------------------------------------- #

def screen_signature(observation: Observation, top_n: int = 30) -> str:
    """Compute a fingerprint of a screen that's robust to small UI churn.

    We hash the SORTED set of (text, resource_id, content_desc) tuples
    of the first `top_n` interactable elements, plus the foreground
    package. This is much more stable than `Observation.screen_hash`
    (which hashes the full XML and changes on every animation tick).
    """
    elements = parse_hierarchy(observation.xml, include_text_labels=True)
    keys: Set[tuple] = set()
    for e in elements[:top_n]:
        keys.add((
            (e.text or "").strip().lower()[:60],
            (e.resource_id or "").strip().lower()[:60],
            (e.content_desc or "").strip().lower()[:60],
        ))
    pkg = (observation.current_app or "").strip().lower()
    payload = repr(sorted(keys)) + "|" + pkg
    return hashlib.sha1(payload.encode("utf-8", "ignore")).hexdigest()[:16]


def _element_label(e: UIElement) -> str:
    """Pick the most useful, stable label for an element."""
    for v in (e.text, e.resource_id, e.content_desc):
        v = (v or "").strip()
        if v and len(v) <= 60:
            return v
    return ""


def _new_anchors(
    pre: Observation,
    post: Observation,
    limit: int = 4,
) -> List[str]:
    """Element labels present AFTER the action that were not present BEFORE.

    These are the strongest signals that the action moved the UI to a
    new state. If the screen didn't change at all, we return an empty
    list (the replayer will fall back to signature comparison).
    """
    pre_labels = {_element_label(e) for e in parse_hierarchy(pre.xml)}
    post_elements = parse_hierarchy(post.xml)

    new_labels: List[str] = []
    for e in post_elements:
        label = _element_label(e)
        if not label or label in pre_labels:
            continue
        # Prefer reasonably short, stable strings; skip long descriptions.
        if 2 <= len(label) <= 40 and label not in new_labels:
            new_labels.append(label)
        if len(new_labels) >= limit:
            break
    return new_labels


# --------------------------------------------------------------------------- #
# Recorder
# --------------------------------------------------------------------------- #

@dataclass
class _Pending:
    """Action awaiting its post-action observation for verification."""
    action_kind: str
    target: str
    target_kind: str
    input_value: str
    pre_obs: Observation
    pre_signature: str
    milestone_id: Optional[int]
    milestone_text: str
    screen_summary: str
    is_recovery: bool


class TaskRecorder:
    """Sits next to the Executor and captures successful actions.

    The Executor calls:
      • `record_attempt(...)`   right BEFORE the action
      • `record_outcome(post)`  right AFTER, with the new observation

    Failed attempts are dropped (we don't want to replay them).
    Recovery actions (popup dismissals) are kept but flagged — the
    replayer will execute them only if the popup actually appears.
    """

    def __init__(
        self,
        goal: str,
        llm_provider: str = "",
        llm_model: str = "",
        plan_milestones: Optional[List[PlanStep]] = None,
    ) -> None:
        self.goal = goal
        self.llm_provider = llm_provider
        self.llm_model = llm_model
        self.plan_milestones = plan_milestones or []
        self._actions: List[RecordedAction] = []
        self._pending: Optional[_Pending] = None
        self._closed = False

    # ---- API used by the Executor --------------------------------------- #

    def record_attempt(
        self,
        *,
        pre_obs: Observation,
        action_kind: str,
        target: str,
        target_kind: str,
        input_value: str,
        milestone_id: Optional[int],
        milestone_text: str,
        screen_summary: str,
        is_recovery: bool,
    ) -> None:
        """Stash the pre-action context. Called BEFORE the device acts."""
        if self._closed:
            return
        self._pending = _Pending(
            action_kind=action_kind,
            target=target,
            target_kind=target_kind,
            input_value=input_value,
            pre_obs=pre_obs,
            pre_signature=screen_signature(pre_obs),
            milestone_id=milestone_id,
            milestone_text=milestone_text,
            screen_summary=screen_summary,
            is_recovery=is_recovery,
        )

    def record_outcome(
        self,
        post_obs: Observation,
        success: bool,
        *,
        progressed: bool = True,
    ) -> None:
        """Finalize the pending attempt. Called AFTER the device acts.

        Only successful actions that visibly advanced the UI are kept.
        Failed attempts, recovery taps, idle waits, and no-op clicks are
        discarded so saved macros stay clean.
        """
        if self._closed or self._pending is None:
            return
        p = self._pending
        self._pending = None
        if not success:
            return
        if p.is_recovery:
            return
        if p.action_kind in ("wait", "give_up"):
            return
        if not progressed:
            log.debug(
                "recorder: dropped step (no UI progress) kind=%s target=%r",
                p.action_kind, p.target,
            )
            return

        anchors = _new_anchors(p.pre_obs, post_obs)
        post_sig = screen_signature(post_obs)
        if (
            p.action_kind in ("click", "type", "scroll_to")
            and post_sig == p.pre_signature
            and not anchors
        ):
            log.debug(
                "recorder: dropped step (screen unchanged, no anchors) target=%r",
                p.target,
            )
            return
        dyn = RecordedAction.detect_dynamic(p.input_value)
        action = RecordedAction(
            step_index=len(self._actions) + 1,
            milestone_id=p.milestone_id,
            milestone_text=p.milestone_text,
            screen_signature=p.pre_signature,
            screen_summary=p.screen_summary,
            action_kind=p.action_kind,
            target=p.target,
            target_kind=p.target_kind,
            input_value=p.input_value,
            is_dynamic=bool(dyn),
            dynamic_fields=dyn,
            verification_anchors=anchors,
            is_recovery=p.is_recovery,
        )
        self._actions.append(action)
        log.debug(
            "recorder: step %d kind=%s target=%r anchors=%s dynamic=%s",
            action.step_index, action.action_kind, action.target,
            action.verification_anchors, action.dynamic_fields,
        )

    def discard_pending(self) -> None:
        """Throw away an in-flight attempt without finalizing it."""
        self._pending = None

    # ---- Output --------------------------------------------------------- #

    def has_actions(self) -> bool:
        return bool(self._actions)

    def build_task(self, *, drop_recovery: bool = False) -> RecordedTask:
        """Bundle everything we recorded into a `RecordedTask`.

        `drop_recovery=True` removes one-off popup dismissals; useful
        when you only want the canonical happy-path macro.
        """
        actions = list(self._actions)
        if drop_recovery:
            actions = [a for a in actions if not a.is_recovery]
            for i, a in enumerate(actions, start=1):
                a.step_index = i

        plan_dump: List[dict] = []
        for s in self.plan_milestones:
            plan_dump.append({
                "step_id": s.step_id,
                "action_description": s.action_description,
                "expected_outcome": s.expected_outcome,
                "is_optional": s.is_optional,
            })

        return RecordedTask(
            goal=self.goal,
            llm_provider=self.llm_provider,
            llm_model=self.llm_model,
            plan_milestones=plan_dump,
            actions=actions,
        )

    def close(self) -> None:
        self._closed = True
